spring:
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active:default}
      label: ${spring.application.name}
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}
        instance-id: ${spring.cloud.consul.discovery.service-name}-1
  application:
    name: MYSOAPCLIENT
server:
  port: 8044


