
package com.kn.springwsdemo.message;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EmployeesPort", targetNamespace = "http://www.kn.com/springsoap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeesPort {


    /**
     * 
     * @param getAllEmployeesRequest
     * @return
     *     returns com.example.consumingwebservice.wsdl.GetEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "getEmployeeResponse", targetNamespace = "http://www.kn.com/springsoap", partName = "getEmployeeResponse")
    public GetEmployeeResponse getAllEmployees(
        @WebParam(name = "getAllEmployeesRequest", targetNamespace = "http://www.kn.com/springsoap", partName = "getAllEmployeesRequest")
        GetAllEmployeesRequest getAllEmployeesRequest);

}
